version: '3.1'
services:
  showcase:
    build: /Users/aleksandrgineyka/Desktop/DEV_P/Showcase/Dockerfile
    image: online-store-image
    container_name: showcase
    ports:
      - "8083:8083"
    depends_on:
      - showcase-db
      - payment-server
      - redis-db
    environment:
      - DB_NAME=showcase
      - DB_HOST=showcase-db
      - DB_PORT=6541
      - POSTGRES_USER=root
        POSTGRES_PASSWORD=root
      - PAYMENT_SERVER_PORT=9091
      - PAYMENT_SERVER_URL=http://payment-server:9091
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379

  payment-server:
    build: /Users/aleksandrgineyka/Desktop/DEV_P/payment-service/Dockerfile
    image: payment-image
    container_name: payment
    ports:
      - "9091:9091"
    depends_on:
      - payment-db
    environment:
      - DB_NAME=payment
      - DB_HOST=payment-db
      - DB_PORT=65426542
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  showcase-db:
    image: postgres:15
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=showcase
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  payment-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  redis-db:
    image: redis:latest
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    container_name: keycloak

# http://localhost:15672/#/exchanges адврес
#  rabbitmq:
#    image: rabbitmq:4.0-management
#    container_name: rabbitmq
#    ports:
#       - "5672:5672"
#       - "15672:15672"
#    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password
##      - RABBITMQ_VIRTUAL_HOST=prod