spring:
  application:
    name: OnlineStore

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/store
#    password: postgres
#    username: postgres

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

      environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

path:
  to:
    dir: C:/store/uploads/