CREATE TABLE IF NOT EXISTS items
(
    Id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Title VARCHAR(250),
    Description VARCHAR(500),
    ImagePath VARCHAR(250),
    Price DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS orders
(
    Id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS order_item
(
    order_id INTEGER REFERENCES orders (id) NOT NULL,
    item_id  INTEGER REFERENCES items (id)  NOT NULL,
    PRIMARY KEY (order_id, item_id)
);

CREATE TABLE IF NOT EXISTS counts
(
    Id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_id  VARCHAR REFERENCES items (id)  NOT NULL
);