spring:
  application:
    name: OnlineStore
  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            authorization-uri: http://localhost:8080/realms/master/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
#            jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
#        registration:
#          keycloak:
#            authorizationGrantType: authorization_code
#            provider: keycloak
#            client-id: showcase
#            client-secret: 1ggXR4DXMmcUFzTfQaSBE5akd5SoSzOr
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: openid, profile, email

    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master # Адрес сервера авторизации для получения токена
        registration:
          yandex: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: showcase
            client-secret: 1ggXR4DXMmcUFzTfQaSBE5akd5SoSzOr
            scope: profile
            clientAuthenticationMethod: client_secret_post

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1

  payment:
    url: ${PAYMENT_SERVER_URL}
#  rabbitmq:
#    username: ${RABBITMQ_DEFAULT_USER}
#    password: ${RABBITMQ_DEFAULT_PASS}
#    virtualHost: ${RABBITMQ_VIRTUAL_HOST}

    data:
      redis:
        host: ${REDIS_HOST}}
        port: ${REDIS_PORT}
    cache:
      redis:
        time-to-live: PT10S



server:
  port: 8081